### PR TITLE
Fix dropbox URLs for external assets

### PR DESCRIPTION
**Pull request by almccon**
Note, eventually we will want to find a better place to host these.

### CODE REVIEW

**Comment by javisantana** [comment]
is this the same than #5 ?

those icons are stored in s3, the urls are replaced here: https://github.com/CartoDB/CartoDB-basemaps/blob/master/util.js#L25

**Comment by almccon** [comment]
No sorry, @javisantana this was a messy pull request. I tried to clean out the #5 stuff.

Commit ef73f22 was all I meant to apply. I didn't realize that util.js is already rewriting them. Should we just simplify everything and use the s3 path in the stylesheets? @bdon what do you think?

**Comment by bdon** [comment]
It seems like the cachebuster code in util.js is necessary, why not just replace the stylesheet links to something like example.com so it's obvious that it will be rewritten?

**Comment by zenitraM** [comment]
Just moved everything to our S3 on https://github.com/CartoDB/CartoDB-basemaps/commit/e73afad85fad8b2c019fa365fb33ab79e7faf686 :smile:

**Comment by almccon** [comment]
Great!

**Pull request closed without merging**
