### PR TITLE
Only labels styles for positron and dark matter

### PR DESCRIPTION
**Pull request by saleiva**

### CODE REVIEW

**Comment by saleiva** [comment]
@javisantana this should have a compatible version with all the new variables updated

**Comment by saleiva** [comment]
@javisantana I think that with this we could close the first version of this layers.
Would be great to have a test-suite to compare tiles after the merge just to be sure we are not breaking the actual tiles (labels and geometry merged)

**Comment by javisantana** [comment]
Ok, do you know any zoom or special zone we should be testing?

**Comment by saleiva** [comment]
to compare with the previous one? the most correct option would be to make a few random requests...

**Comment by javisantana** [comment]
comparing the light_all with the previous one seems there are changes: 

http://bl.ocks.org/javisantana/raw/9c34e497a5f93f113c88/#staging_light

**Comment by saleiva** [comment]
Yes its normal. To test backwards compatibility we should compare the
existing ones (light_all) with the light_all on this new version.

**Comment by javisantana** [comment]
that's the test

**Comment by saleiva** [comment]
Impossible :(.
Something is wrong in local was not like that

**Comment by javisantana** [comment]
try again, I don't see any difference

**Comment by saleiva** [comment]
Deal :)

**Comment by pnorman** [comment]
Fixed in #59

**Pull request closed without merging**
